CREATE TABLE noaa_ghcn (
    ghcn_id SERIAL CONSTRAINT ghcn_key PRIMARY KEY,
    site_id INTEGER REFERENCES sites (site_id),
    station CHAR(17),
    date_time TIMESTAMP WITH TIME ZONE,
    SX32 INTEGER,
    SX32_mflag CHAR, 
    SX32_qflag CHAR, 
    SX32_sflag CHAR, 
    SX32_tobs INTEGER, 
    SX33 INTEGER,
    SX33_mflag CHAR,
    SX33_qflag CHAR,
    SX33_sflag CHAR,
    SX33_tobs INTEGER,
    SX31 INTEGER,
    SX31_mflag CHAR,
    SX31_qflag CHAR,
    SX31_sflag CHAR,
    SX31_tobs INTEGER,
    SN32 INTEGER,
    SN32_mflag CHAR,
    SN32_qflag CHAR,
    SN32_sflag CHAR,
    SN32_tobs INTEGER,
    SN33 INTEGER,
    SN33_mflag CHAR,
    SN33_qflag CHAR,
    SN33_sflag CHAR,
    SN33_tobs INTEGER,
    SN31 INTEGER,
    SN31_mflag CHAR,
    SN31_qflag CHAR,
    SN31_sflag CHAR,
    SN31_tobs INTEGER,
    MDPR INTEGER,
    MDPR_mflag CHAR,
    MDPR_qflag CHAR,
    MDPR_sflag CHAR,
    MDPR_tobs INTEGER,
    DAPR INTEGER,
    DAPR_mflag CHAR,
    DAPR_qflag CHAR,
    DAPR_sflag CHAR,
    DAPR_tobs INTEGER,
    PRCP INTEGER,
    PRCP_mflag CHAR,
    PRCP_qflag CHAR,
    PRCP_sflag CHAR,
    PRCP_tobs INTEGER,
    SNWD INTEGER,
    SNWD_mflag CHAR,
    SNWD_qflag CHAR,
    SNWD_sflag CHAR,
    SNWD_tobs INTEGER,
    SNOW INTEGER,
    SNOW_mflag CHAR,
    SNOW_qflag CHAR,
    SNOW_sflag CHAR,
    SNOW_tobs INTEGER,
    TMAX INTEGER,
    TMAX_mflag CHAR,
    TMAX_qflag CHAR,
    TMAX_sflag CHAR,
    TMAX_tobs INTEGER,
    TMIN INTEGER,
    TMIN_mflag CHAR,
    TMIN_qflag CHAR,
    TMIN_sflag CHAR,
    TMIN_tobs INTEGER,
    TOBS INTEGER,
    TOBS_mflag CHAR,
    TOBS_qflag CHAR,
    TOBS_sflag CHAR,
    TOBS_tobs INTEGER
    );

ALTER TABLE noaa_ghcn OWNER TO postgres;

COMMENT ON TABLE noaa_ghcn IS 'NOAA DAILY GLOBAL HISTORICAL CLIMATOLOGY NETWORK (GHCN-DAILY). See http://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt and http://www1.ncdc.noaa.gov/pub/data/cdo/documentation/GHCND_documentation.pdf';
COMMENT ON COLUMN noaa_ghcn.site_id IS 'Foreign key from sites table';
COMMENT ON COLUMN noaa_ghcn.station IS 'NOAA Station Identifier. 17 Characters';
COMMENT ON COLUMN noaa_ghcn.date_time IS 'UTC Timestamp';
COMMENT ON COLUMN noaa_ghcn.SX32 IS 'Maximum Soil Temperature, bare earth, 10cm';
COMMENT ON COLUMN noaa_ghcn.SX32_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SX32_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SX32_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SX32_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.SX33 IS 'Maximum Soil Temperature, bare earth, 20cm depth';
COMMENT ON COLUMN noaa_ghcn.SX33_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SX33_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SX33_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SX33_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.SX31 IS 'Maximum Soil temperature, bare earth, 5cm depth';
COMMENT ON COLUMN noaa_ghcn.SX31_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SX31_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SX31_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SX31_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.SN32 IS 'Minimum Soil Temperature, bare earth, 10cm depth';
COMMENT ON COLUMN noaa_ghcn.SN32_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SN32_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SN32_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SN32_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.SN33 IS 'Minimum Soil Temperature, bare earth, 20cm depth';
COMMENT ON COLUMN noaa_ghcn.SN33_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SN33_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SN33_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SN33_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.SN31 IS 'Minimum Soil Temperature, bare earth, 5cm';
COMMENT ON COLUMN noaa_ghcn.SN31_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SN31_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SN31_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SN31_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.MDPR IS 'Multiaday Precipitation total (tenths of mm)';
COMMENT ON COLUMN noaa_ghcn.MDPR_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.MDPR_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.MDPR_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.MDPR_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.DAPR IS 'Number of days included in the multiday precipitation total (MDPR)';
COMMENT ON COLUMN noaa_ghcn.DAPR_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.DAPR_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.DAPR_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.DAPR_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.PRCP IS 'Precipitation (tenths of mm)';
COMMENT ON COLUMN noaa_ghcn.PRCP_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.PRCP_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.PRCP_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.PRCP_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.SNWD IS 'SNWD = Snow depth';
COMMENT ON COLUMN noaa_ghcn.SNWD_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SNWD_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SNWD_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SNWD_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.SNOW IS 'Snowfall (mm)';
COMMENT ON COLUMN noaa_ghcn.SNOW_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.SNOW_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.SNOW_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.SNOW_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.TMAX IS 'Maximum temperature (Celsius, degrees to tenth)';
COMMENT ON COLUMN noaa_ghcn.TMAX_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.TMAX_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.TMAX_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.TMAX_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.TMIN IS 'Minimum temperature (Celsius, degrees to tenth)';
COMMENT ON COLUMN noaa_ghcn.TMIN_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.TMIN_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.TMIN_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.TMIN_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
COMMENT ON COLUMN noaa_ghcn.TOBS IS 'Temperature at time of observation (celsius, degrees to tenth)';
COMMENT ON COLUMN noaa_ghcn.TOBS_mflag IS 'Blank = no measurement information applicable; A = value in precipitation or snow is a multi-day total, accumulated since last measurement (used on Daily Form pdf file); B = precipitation total formed from two 12-hour totals; D = precipitation total formed from four six-hour totals; K = converted from knots; L = temperature appears to be lagged with respect to reported; hour of observation; O = converted from oktas; P = identified as missing presumed zero in DSI 3200 and 3206; T = trace of precipitation, snowfall, or snow depth; W = converted from 16-point WBAN code (for wind direction)';
COMMENT ON COLUMN noaa_ghcn.TOBS_qflag IS 'Blank = did not fail any quality assurance check; D = failed duplicate check; G = failed gap check; I = failed internal consistency check; K = failed streak/frequent-value check; L = failed check on length of multiday period; M = failed mega-consistency check; N = failed naught check; O = failed climatological outlier check; R = failed lagged range check; S = failed spatial consistency check; T = failed temporal consistency check; W = temperature too warm for snow; X = failed bounds check; Z = flagged as a result of an official Datzilla investigation';
COMMENT ON COLUMN noaa_ghcn.TOBS_sflag IS 'Blank = No source (i.e., data value missing); 0 = U.S. Cooperative Summary of the Day (NCDC DSI-3200); 6 = CDMP Cooperative Summary of the Day (NCDC DSI-3206); 7 = U.S. Cooperative Summary of the Day -- Transmitted via WxCoder3 (NCDC DSI-3207); A = U.S. Automated Surface Observing System (ASOS) real-time data (since January 1, 2006); a = Australian data from the Australian Bureau of Meteorology; B = U.S. ASOS data for October 2000-December 2005 (NCDC DSI-3211); b = Belarus update; E = European Climate Assessment and Dataset (Klein Tank et al., 2002); F = U.S. Fort data; G = Official Global Climate Observing System (GCOS) or other government-supplied data; H = High Plains Regional Climate Center real-time data; I = International collection (non U.S. data received through personal contacts); K = U.S. Cooperative Summary of the Day data digitized from paper observer forms (from 2011 to present); M = Monthly METAR Extract (additional ASOS data); N = Community Collaborative Rain, Hail,and Snow (CoCoRaHS); Q = Data from several African countries that had been quarantined, that is, withheld from public release until permission was granted from the respective meteorological services; R = NCDC Reference Network Database (Climate Reference Network and Historical Climatology Network-Modernized); r = All-Russian Research Institute of Hydrometeorological Information-World Data Center; S = Global Summary of the Day (NCDC DSI-9618) NOTE: S values are derived from hourly synoptic reports exchanged on the Global Telecommunications System (GTS). Daily values derived in this fashion may differ significantly from true daily data, particularly for precipitation(i.e., use with caution).; u = Ukraine update; W = WBAN/ASOS Summary of the Day from NCDCs Integrated Surface Data (ISD); X = U.S. First-Order Summary of the Day (NCDC DSI-3210); Z = Datzilla official additions or replacements; z = Uzbekistan update';
COMMENT ON COLUMN noaa_ghcn.TOBS_tobs IS 'Time of observation, 24 hr clock time. 2 digit hour, 2 digit minute';
 