#' @title Plot Falmouth Data
#'
#' @description
#' \code{matplotfalmouth} Matrix plot of falmouth data returned by the getfalmouth function
#' @family plot functions
#' 
#' @details
#' This is a function to trivialize plotting the Falmouth data from the rfalmouth view.
#' The inputs are a falmouth table generated by the getfalmouth() function in the rkori package
#' And the database view rfalmouth must be present. Note that the command 'Sys.setenv(TZ='GMT')' should
#' always be run before querying the database.
#' 
#' @param falmouth (dataframe) A dataframe generated by the getfalmouth() function
#' @param scale_type (str) A string value giving the scales value for the facet_wrap() function. Valid values are "fixed", "free", "free_x", "free_y". Default value is "free_y".
#' @param data point_size (numeric) A numeric value giving the point size for plots. Defaults to 1, bt may need adjusting depending on the size of the date range plotted.
#' @return This function returns nothing
#' @examples
#' require(RPostgreSQL)
#' require(ggplot2)
#' con <- dbConnect(PostgreSQL(), host="localhost", user="wkp_user", password="wkp_user", dbname="wkp_hrdb")
#' f <- getfalmouth(con, "2012-11-01 00:00:00", "2012-12-01 00:00:00")
#' matplotfalmouth(f)
#' @name matplotfalmouth




matplotfalmouth <- function(falmouth, scale_type="free_y", point_size=1) {
    require(RPostgreSQL)
    require(ggplot2)
    require(ggthemes)
    require(scales)
    base_title = "Falmouth Matrix Plot \n MINDT to MAXDT"
    mindt = min(falmouth$date_time)
    maxdt = max(falmouth$date_time)
    base_title = gsub("MINDT", mindt, base_title)
    base_title = gsub("MAXDT", maxdt, base_title)

    plt <- ggplot(falmouth, aes(x=date_time, y=val, col=var))
    fwrap = facet_wrap(site_name~var, scales=scale_type, ncol=length(levels(falmouth$var)), nrow=length(levels(falmouth$site_name)))
    plt + 
        geom_point(alpha=1/5, size=point_size) +
        fwrap + 
        xlab("") + ylab("") +
        scale_color_discrete(name="Site Name") +
        ggtitle(base_title) + 
        guides(colour = guide_legend(override.aes = list(size=4, alpha=1)))
    }

